name: EAS Build

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Build profile to use'
        required: true
        type: choice
        options:
          - development
          - preview
          - production
        default: preview
      platform:
        description: 'Platform to build for'
        required: true
        type: choice
        options:
          - all
          - ios
          - android
        default: all

jobs:
  build:
    name: Build on EAS
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build with EAS
        run: |
          if [ "${{ github.event.inputs.platform }}" = "all" ]; then
            eas build --profile ${{ github.event.inputs.profile }} --non-interactive
          else
            eas build --platform ${{ github.event.inputs.platform }} --profile ${{ github.event.inputs.profile }} --non-interactive
          fi

