name: Security Audit

on:
  schedule:
    # Run weekly on Monday at 9 AM
    - cron: '0 9 * * 1'
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run security audit
        run: |
          # Bun doesn't have audit yet, but we can check for known vulnerabilities
          bun install --frozen-lockfile
          
          echo "🔒 Security scan completed"
          echo "📦 Checking for outdated packages..."

      - name: Check outdated packages
        id: outdated
        run: |
          bun outdated > outdated.txt 2>&1 || true
          if [ -s outdated.txt ]; then
            echo "has_outdated=true" >> $GITHUB_OUTPUT
          else
            echo "has_outdated=false" >> $GITHUB_OUTPUT
          fi

      - name: Create issue if vulnerabilities found
        if: github.event_name != 'pull_request' && steps.outdated.outputs.has_outdated == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const outdated = fs.readFileSync('outdated.txt', 'utf8');
            
            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'security,dependencies'
            });
            
            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🔒 Security: Outdated dependencies detected',
                body: `## Outdated Dependencies\n\n\`\`\`\n${outdated}\n\`\`\`\n\n**Action Required:** Review and update dependencies.`,
                labels: ['security', 'dependencies']
              });
            }

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
